# Generated by Django 5.0.3 on 2025-12-09 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_sn', models.CharField(db_index=True, max_length=30, verbose_name='单号')),
                ('role', models.CharField(max_length=30, verbose_name='审批角色')),
                ('seq', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('action', models.CharField(blank=True, choices=[('agree', '同意'), ('reject', '驳回')], max_length=10, verbose_name='动作')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='意见')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='单号')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('running', '审批中'), ('done', '完成'), ('reject', '驳回')], default='draft', max_length=10, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expense_type', models.CharField(choices=[('travel', '差旅费'), ('office', '办公费'), ('entertainment', '招待费'), ('other', '其他')], max_length=20, verbose_name='报销类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('description', models.TextField(verbose_name='描述')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='附件')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '报销单',
                'verbose_name_plural': '报销单',
            },
        ),
        migrations.CreateModel(
            name='FlowTpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='流程名')),
                ('nodes', models.JSONField(default=list, verbose_name='节点')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='适用类型')),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='单号')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('running', '审批中'), ('done', '完成'), ('reject', '驳回')], default='draft', max_length=10, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('leave_type', models.CharField(choices=[('sick', '病假'), ('annual', '年假'), ('affair', '事假'), ('marriage', '婚假'), ('maternity', '产假'), ('other', '其他')], max_length=10, verbose_name='请假类型')),
                ('start', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.TextField(verbose_name='事由')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '请假单',
                'verbose_name_plural': '请假单',
            },
        ),
    ]
