# Generated by Django 5.0.3 on 2025-12-13 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_leave_update_time_delete_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='update_time',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='单号')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('running', '审批中'), ('done', '完成'), ('reject', '驳回')], default='draft', max_length=10, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expense_type', models.CharField(choices=[('travel', '差旅费'), ('office', '办公费'), ('entertainment', '招待费'), ('other', '其他')], max_length=20, verbose_name='报销类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('description', models.TextField(verbose_name='描述')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='附件')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '报销单',
                'verbose_name_plural': '报销单',
            },
        ),
    ]
