# Generated by Django 5.0.3 on 2025-12-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_max_size', models.PositiveIntegerField(default=512, verbose_name='头像最大尺寸(KB)')),
                ('avatar_ext', models.CharField(default='jpg,jpeg,png', max_length=100, verbose_name='允许头像后缀')),
                ('page_size', models.PositiveIntegerField(default=15, verbose_name='默认分页条数')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
