# Generated by Django 5.0.3 on 2025-12-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('trial', '试用期'), ('formal', '正式'), ('intern', '实习'), ('resign', '离职')], default='trial', max_length=10, verbose_name='状态'),
        ),
    ]
