# Generated by Django 5.0.3 on 2025-12-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='班次名')),
                ('on_duty', models.TimeField(verbose_name='上班打卡时间')),
                ('off_duty', models.TimeField(verbose_name='下班打卡时间')),
                ('allow_early', models.PositiveSmallIntegerField(default=30, verbose_name='允许提前分钟')),
                ('allow_late', models.PositiveSmallIntegerField(default=30, verbose_name='允许晚到分钟')),
            ],
        ),
    ]
