# Generated by Django 5.0.3 on 2025-12-09 23:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='打卡日期')),
                ('punch_in', models.DateTimeField(blank=True, null=True, verbose_name='上班打卡')),
                ('punch_out', models.DateTimeField(blank=True, null=True, verbose_name='下班打卡')),
                ('state', models.CharField(choices=[('ok', '正常'), ('late', '迟到'), ('early', '早退'), ('lack', '缺卡'), ('out', '外勤')], default='lack', max_length=10, verbose_name='结果')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('gps', models.CharField(blank=True, max_length=50, verbose_name='GPS')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
